version: '3'
services:
  srt:
    container_name: uniobs-srt
    image: ravenium/srt-live-server
    ports: 
      - "2020:1935/udp"
    volumes:
      - ./sls.conf:/etc/sls/sls.conf
      - ./logs:/logs
    restart: unless-stopped